maintainer       "Blue Box Group, LLC"
maintainer_email "support@bluebox.net"
license          "Apache 2.0"
description      "Installs Git"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.rdoc'))
version          "0.0.1"
supports         "centos"
supports         "rhel"
supports         "scientific"
supports         "ubuntu"
supports         "debian"
